package com.example.apple_diseases_detection.presentation.components.ui.theme

import androidx.compose.ui.graphics.Color

val white = Color(0xFFFFFFFF)
val black = Color(0xFF000000)
val transparent = Color(0x00000000)

val primary = Color(0xFF296A48)
val onPrimary = Color(0xFFFFFFFF)
val primaryContainer = Color(0xFFADF2C6)
val onPrimaryContainer = Color(0xFF075232)
val secondary = Color(0xFF006A61)
val onSecondary = Color(0xFFFFFFFF)
val secondaryContainer = Color(0xFF9EF2E5)
val onSecondaryContainer = Color(0xFF005049)
val tertiary = Color(0xFF3B6471)
val onTertiary = Color(0xFFFFFFFF)
val tertiaryContainer = Color(0xFFBFE9F8)
val onTertiaryContainer = Color(0xFF224C58)
val error = Color(0xFFBA1A1A)
val onError = Color(0xFFFFFFFF)
val errorContainer = Color(0xFFFFDAD6)
val onErrorContainer = Color(0xFF93000A)
val background = Color(0xFFF6FBF4)
val onBackground = Color(0xFF171D19)
val surface = Color(0xFFF6FBF4)
val onSurface = Color(0xFF171D19)
val surfaceVariant = Color(0xFFDCE5DC)
val onSurfaceVariant = Color(0xFF404942)
val outline = Color(0xFF717972)
val outlineVariant = Color(0xFFC0C9C0)
val scrim = Color(0xFF000000)
val inverseSurface = Color(0xFF2C322D)
val inverseOnSurface = Color(0xFFEDF2EB)
val inversePrimary = Color(0xFF92D5AB)
val surfaceDim = Color(0xFFD6DBD5)
val surfaceBright = Color(0xFFF6FBF4)
val surfaceContainerLowest = Color(0xFFFFFFFF)
val surfaceContainerLow = Color(0xFFF0F5EE)
val surfaceContainer = Color(0xFFEAEFE8)
val surfaceContainerHigh = Color(0xFFE4EAE3)
val surfaceContainerHighest = Color(0xFFDFE4DD)