package com.example.apple_diseases_detection.presentation.components.ui.theme

import androidx.compose.ui.graphics.Color

val white = Color(0xFFFFFFFF)
val black = Color(0xFF000000)
val transparent = Color(0x00000000)

val primaryLight = Color(0xFF296A48)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFADF2C6)
val onPrimaryContainerLight = Color(0xFF075232)
val secondaryLight = Color(0xFF006A61)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFF9EF2E5)
val onSecondaryContainerLight = Color(0xFF005049)
val tertiaryLight = Color(0xFF3B6471)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFBFE9F8)
val onTertiaryContainerLight = Color(0xFF224C58)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF6FBF4)
val onBackgroundLight = Color(0xFF171D19)
val surfaceLight = Color(0xFFF6FBF4)
val onSurfaceLight = Color(0xFF171D19)
val surfaceVariantLight = Color(0xFFDCE5DC)
val onSurfaceVariantLight = Color(0xFF404942)
val outlineLight = Color(0xFF717972)
val outlineVariantLight = Color(0xFFC0C9C0)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2C322D)
val inverseOnSurfaceLight = Color(0xFFEDF2EB)
val inversePrimaryLight = Color(0xFF92D5AB)
val surfaceDimLight = Color(0xFFD6DBD5)
val surfaceBrightLight = Color(0xFFF6FBF4)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF0F5EE)
val surfaceContainerLight = Color(0xFFEAEFE8)
val surfaceContainerHighLight = Color(0xFFE4EAE3)
val surfaceContainerHighestLight = Color(0xFFDFE4DD)